defaults:
  - submitit_slurm

timeout_min: 60
gpus_per_node: 1
tasks_per_node: 1
cpus_per_task: 10
gres: "gpu:${gpus}"
qos: qos_gpu-dev
additional_parameters:
  ntasks-per-node: 1
  cpus-per-task: 10
  account: hih@gpu
  distribution: "block:block"
  hint: nomultithread
  time: "${hours}:00:00"
setup:
  - "#SBATCH -C v100-32g"
  - "cd $WORK/submission-scripts/jean_zay/env_configs"
  - . ${project}.sh