defaults:
  - submitit_slurm

timeout_min: 60
gpus_per_node: 1
tasks_per_node: 1
cpus_per_task: 10
mem_gb: 40
cpus_per_gpu: 10
gpus_per_task: ${hydra.launcher.gpus_per_node}
mem_per_gpu: 40
mem_per_cpu: 4
additional_parameters:
  ntasks-per-node: ${hydra.launcher.tasks_per_node}
  cpus-per-task: ${hydra.launcher.cpus_per_task}
  account: hih@gpu
  distribution: "block:block"
  hint: nomultithread
  time: "${hours}:00:00"
  qos: qos_gpu-dev
  gres: "gpu:${hydra.launcher.gpus_per_node}"
setup:
  - "#SBATCH -C v100-32g"
  - "cd $WORK/submission-scripts/jean_zay/env_configs"
  - . ${project}.sh